# Generated by Django 4.0 on 2021-12-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
        ('wishlist', '0002_rename_user_wishlist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='My Wishlist', max_length=15),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
