# Generated by Django 4.0 on 2021-12-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
        ('wishlist', '0003_remove_wishlist_product_wishlist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
