# Generated by Django 4.0 on 2021-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
        ('wishlist', '0004_alter_wishlist_name_alter_wishlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product'),
        ),
    ]
